export const LOG_IN = 'LOG_IN';
export const LOG_OUT = 'LOG_OUT';
export const SAVE_CATEGORIES = 'SAVE_CATEGORIES';
export const SAVE_SONG_INFO = 'SAVE_SONG_INFO';
export const TOGGLE_PLAY_STATUS = 'TOGGLE_PLAY_STATUS';
export const UPDATE_SONG_PROGRESS = 'UPDATE_SONG_PROGRESS';
export const UPDATE_SONG_DURATION = 'UPDATE_SONG_DURATION';
